### ISSUE TITLE
Parse error of coins file

### ISSUE THREAD

**Issue by maxcado** [jl777/libnspv#147]
Hello, 
First let me say thank you for this wallet. It is nicely done. I've installed the wallet. When I run ./nspv file I get "parse error of coins file." The ./bitcointool works perfect.

**Comment by jl777** [comment]
do you have a file called "coins" in the directory you are launching nspv from?

**Comment by maxcado** [comment]
Yes, there is a file called "coins" and I did input the data per your instructions on the readme. But I didn't make all the adjustments in the coins file. I removed a lot of coins listed in the file. I put in some of the data that I could find.

**Comment by jl777** [comment]
it seems your modifications to the coins file has a JSON error in it. use jsonlint.com or equivalent JSON parser to find and fix it. it must be valid JSON. probably a missing comma or something like that
