### ISSUE TITLE
nspv_spend call komodod crash

### ISSUE THREAD

**Issue by SirSevenG** [jl777/libnspv#39]
`./komodod -nSPV=1`

komodo daemon may crash on nspv_spend call.

Script example to help with reproduction:
```shell
#!/bin/bash

./komodo-cli nspv_login  _wif_
sleep 1
while :
do
  ./komodo-cli nspv_logout
  sleep 1
  ./komodo-cli nspv_login  _wif_
  sleep 1
  ./komodo-cli nspv_spend  _spend_addr_  0.01
  sleep 1
done
```
After 2 to 6 iterations you should get segfault.

*Note:* komodod does not crash if you just do:
nspv_login
snpv_spend in loop
Issue happens only in case of successive log_in log_out log_in calls. 

backtrace examples:
https://paste.ubuntu.com/p/9CzV52djhv/

**Comment by SirSevenG** [comment]
Same behaviour with libnspv.

backtrace examples:
https://paste.ubuntu.com/p/SVZHW53cYn/

Script to repeat:
```shell
#!/bin/bash

curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "login", "params": ["_wif_"] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/

while :
do
  curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "logout", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/
  sleep 1
  curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "login", "params": ["_wif_"] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/
  sleep 1
  curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "spend", "params": ["_address_", 0.01]}' -H 'content-type: text/plain;' http://127.0.0.1:7771/
  sleep 1
done

```

Might require up to 10 iterations.

**Comment by jl777** [comment]
does this crash still happen with latest version?

**Comment by SirSevenG** [comment]
This exact crash does not happen now.

Another one now happens reliably(could not catch it before in reproducible manner).
Trying to use ~38 utxos as input for single transaction results in crash:
https://paste.ubuntu.com/p/R7v2ZVbMzc/

On libnspv at least, rechecking komodod -nSPV=1 atm.

UPD: komodod does not crash in either scenario.

**Comment by jl777** [comment]
pushed fix for crash

**Comment by SirSevenG** [comment]
Fixed.
